apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.commonConfigMap }}
data:
  APP_NAME: 'confixa backend microservices'
  NODE_ENV: 'production'
  ADD_BASEURL_PREFIX: 'true'
  BASE_URL: ''
  PORT: '5001'
  PYTHON_PORT: '5002'
  FLASK_ENV: 'production'
  PARTIAL_ON_BOARDING: 'false'

  # REDIS
  REDIS_INIT: 'true'
  REDIS_PORT: '6379'
  REDIS_DB: ''
  
  # SECURITY
  keyCloakInit: 'false'

  # Signin Flow
  AUTHENTICATION_INTERNAL_ALLOW: 'true'
  JWTALGORITHM: 'HS256'
  AUTHENTICATION_JWT_SECRET_KEY: 'hfekj93f74th2bed82733idnesfeo'
  JWT_EXPIRY_IN_SECONDS: '86400000'
  VALIDATION_SECRET: 'ConfixaHelmChart'
  
  # OPEN AI
  GPT_MODEL_NAME: 'gpt-4-0125-preview'

  # MONGODB
  MONGO_INIT: 'true'
  
  # RABBITMQ
  TASK_ID: "c1"
  ACK_TASK_ID: "ca1"
  WORKER_TYPE: "consumer"
  RABBITMQ_INIT : 'true'
  RABBITMQ_PROTOCOL : "amqp"
  RABBITMQ_USER : "admin"
  RABBITMQ_PORT : '5672'
  RABBITMQ_VHOST : "/"

  # ARGOCD
  ARGOCD_USERNAME : "admin"
  
  # MONITORING
  # GCP
  MONITORING_URL : 'https://monitoring.googleapis.com/v3/'
  MONITORING_DURATION : 7d
  MONITORING_SVC_ACC_KEY : '{}'
  MONITORING_SCOPE : 'https://www.googleapis.com/auth/cloud-platform'
  GCP_PROJECT : ''

  # HELM VERSION
  ARTIFACT_HUB_URL : 'https://artifacthub.io/api/v1/packages/helm/bitnami'
  
  # MICROSERVICE URL
  FRONTEND_URL: '{{ .Values.service.url.frontend }}'
  BACKEND_URL: '{{ .Values.service.url.backend }}'
  CONFIXA_API_URL: '{{ .Values.service.url.backend }}'
  CONFIXA_GITHUB_API_URL: '{{ .Values.service.url.backend }}'
  CONFIXA_ARGO_API_URL: '{{ .Values.service.url.backend }}'
  CONFIXA_ARGO_API_DOMAIN_BASED_URL: '{{ .Values.service.url.backend }}'
  CONFIXA_LLM_KUMA_URL: '{{ .Values.service.url.backend }}'
  CONFIXA_LLM_KUMA_FLASK_PATHNAME: 'getLLMResponse'
  CONFIXA_KUBE_COST_API_URL:  '{{ .Values.service.url.kubeCost }}'
  ARGOCD_URL: '{{ .Values.service.url.argocd }}'
  REDIRECT_URI: 'https://confixa-api.wohlig.com'
  
  # ARTIFACT
  ARTIFACT_SECRET_NAME: 'artifact'
  
  # VERBIAGE TEXT
  WORKFLOW_MESSAGE: 'Workflow automation enabled through Confixa.'

  # UPTIME KUMA
  UPTIME_KUMA_RETRY_INTERVAL: '300'
  UPTIME_KUMA_MAX_RETRIES: '100000'

  # APM
  APM_ENABLE: 'false'

  # NODEMAILER
  MAILER_INIT: 'true'
  
  # GITHUB JOB RUNS ON
  JOB_RUNS_ON_TYPE: 'ubuntu'
  JOB_RUNS_ON_VERSION: '24.04'

  # TOOLS HANDLING ON/OFF
  HEALTH_CHECK_ENABLED: "true"
  
  # DEBUG FOR PYTHON
  PYTHON_DEBUGGER: 'false'