{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace "rabbitmq-password-secret" }}
{{- $rmPassword := "" }}
{{- if $existingSecret }}
  {{- $rmPassword = index $existingSecret.data "rabbitmq-password" }}
{{- else }}
  {{- $rmPassword = randAlphaNum 16 | b64enc | quote }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-password-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  rabbitmq-password: {{ $rmPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-password-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  redis-password: {{ randAlphaNum 16 | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: artifact
  namespace: {{ .Release.Namespace }}
type: Opaque