{{- $existingMainSecret := lookup "v1" "Secret" .Release.Namespace .Values.passwordSecretsManagerName }}
{{- $mongoPassword := "" }}
{{- $mongoRootPassword := "" }}
{{- if $existingMainSecret }}
  {{- $mongoPassword = index $existingMainSecret.data "mongodbPassword" | toString }}
  {{- $mongoRootPassword = index $existingMainSecret.data "mongodbRootPassword" | toString }}
{{- else }}
  {{- $mongoPassword = randAlphaNum 16 | b64enc }}
  {{- $mongoRootPassword = randAlphaNum 16 | b64enc }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.passwordSecretsManagerName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  redisHost: {{ printf "%s.%s.svc.cluster.local" .Values.redis.service.name .Release.Namespace | b64enc }}
  rabbitMQHost: {{ printf "%s.%s.svc.cluster.local" .Values.rabbitmq.service.name .Release.Namespace | b64enc }}
  mongodbPassword: {{ $mongoPassword }}
  mongodbRootPassword: {{ $mongoRootPassword }}
  mongodbRootHost: {{ printf "mongodb://%s:%s@%s.%s.svc.cluster.local:27017/%s?authSource=admin" .Values.mongodb.auth.rootUser ($mongoRootPassword | b64dec) .Values.mongodb.service.name .Release.Namespace .Values.mongodb.auth.rootDatabase | b64enc }}
  llmKumaHost: {{ printf "http://%s.%s.svc.cluster.local" .Values.llmKumaApiGateway.service.name .Release.Namespace | b64enc }}