apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.passwordSecretsManagerName }}
type: Opaque
data:
  redisPassword: {{ .Values.redis.auth.password | b64enc }}
  argocdPassword: {{ .Values.argocd.config.secret.argocdServerAdminPassword | b64enc }}
  rabbitmqPassword: {{ .Values.rabbitmq.auth.password | b64enc }}
  mongodbRootPassword: {{ .Values.mongodb.auth.rootPassword | b64enc }}
  mongodbUsersPassword: {{ .Values.mongodb.auth.passwords | join "," | b64enc }}