apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.passwordSecretsManagerName }}
type: Opaque
data:
  redisHost: {{ printf "%s.%s.svc.cluster.local" .Values.redis.service.name .Release.Namespace | b64enc }}
  rabbitMQHost: {{ printf "%s.%s.svc.cluster.local" .Values.rabbitmq.service.name .Release.Namespace | b64enc }}
  mongodbPassword: {{- $password := randAlphaNum 16 | b64enc }}
  mongodbRootPassword: {{ $password }}
  mongodbRootHost: {{ printf "mongodb://%s:%s@%s.%s.svc.cluster.local:27017/%s?authSource=admin" .Values.mongodb.auth.rootUser ($password | b64dec) .Values.mongodb.service.name .Release.Namespace .Values.mongodb.auth.rootDatabase | b64enc }}