{{- if .Values.frontend.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.frontend.configMapRef }}
data:
  REACT_APP_API_URL: 'http://localhost:5001/'
  REACT_APP_LICENSE_API_URL: 'https://confixa-api.wohlig.com/'
  REACT_APP_THIRD_PARTY_AUTH_APP_URL: 'https://confixa-api.wohlig.com/'
  
  REACT_APP_REDIRECT_URL: 'http://localhost:5000/'
  REACT_APP_REDIRECT_PATHNAME: 'sign-in'

  REACT_APP_KEYCLOAK_URL: 'http://localhost:8080'
  REACT_APP_KEYCLOAK_REALM: 'confixa'
  REACT_APP_KEYCLOAK_AUTH_PATHNAME_1: '/realms/'
  REACT_APP_KEYCLOAK_AUTH_PATHNAME_2: '/protocol/openid-connect/auth'
  REACT_APP_KEYCLOAK_ADMIN_PATHNAME_1: '/admin/master/console/#/'
  REACT_APP_KEYCLOAK_ADMIN_PATHNAME_2: '/users'

  REACT_APP_ARGOCD_INVITE_URL: 'https://argo-cd.readthedocs.io/en/release-2.0/user-guide/private-repositories/'
  REACT_APP_GITHUB_ACCESS_TOKENS_URL: 'https://docs.github.com/en/enterprise-server@3.9/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens'
  REACT_APP_CLOUD_ARTIFACT_REGISTRY: 'https://cloud.google.com/artifact-registry/docs/repositories/create-repos'
  REACT_APP_AWS_DOCKER_REGISTRY: 'https://docs.aws.amazon.com/AmazonECR/latest/public/public-repository-create.html'
  REACT_APP_COST_OPTIMIZE_DOCUMENTATION_URL: ''

  REACT_APP_ENVIRONMENT: 'production'
  PORT: '3001'
  PROTOCOL: 'https'
  HOST: 'localhost'
  REACT_APP_CONFIXA_WEB_URL: 'https://confixa.com/'
  REACT_APP_RESPONSE_TYPE: 'code'
  REACT_APP_CLIENT_ID: 'frontend'
  REACT_APP_SCOPE: 'openid'

  REACT_APP_KIBANA: ''
  REACT_APP_KIBANA_CD_PIPELINE_PATHNAME: 'app/r/s/JB0Xj'
  REACT_APP_KIBANA_FRAME_PATHNAME: 'app/r/s/9j9VX'
  REACT_APP_KIBANA_KUBERNETES_NEW_FRAME_PATHNAME: 'app/r/s/XmLro'

  REACT_APP_SIMMMPLE_LICENSES: ''
  REACT_APP_SIMMMPLE_TERMS_SERVICE: ''
  REACT_APP_HORIZON_UI: ''

  # ON OFF / COMMENT UNCOMMENT BASED ON REQUIREMENT
  REACT_APP_KEYCLOAK_INIT: 'false'
  REACT_APP_PARTIAL_ON_BOARDING: 'true'
  REACT_APP_PRIVATE_SERVICE_ACTIVE: 'false'
  REACT_APP_BACKGROUND_WORKERS_ACTIVE: 'false'
  REACT_APP_BLUEPRINTS_ACTIVE: 'false'
  REACT_APP_SHOW_CHAT_BOAT: 'true'
  # REACT_APP_SHOW_MONITORING_CARD: 'true'
  # REACT_APP_UPTIME_URL: 'http://localhost:3001/'
  REACT_APP_ARGOCD_URL: 'http://localhost:3000/'
  # REACT_APP_KUBERNETES_DASHBOARD_URL: 'http://localhost:9091/'
  # REACT_APP_KUBECOST_URL: 'http://localhost:9090/'
  # ON OFF / COMMENT UNCOMMENT BASED ON REQUIREMENT END

  # REACT_APP_UPTIME_MANAGE_PATHNAME: 'manage-status-page'
  REACT_APP_UPTIME_MANAGE_PATHNAME: 'status/confixa-status'
  REACT_APP_UPTIME_STATUS_PATHNAME: 'status'

  REACT_APP_ARGOCD_PATHNAME: 'auth/login'

  REACT_APP_KUBERNETES_DASHBOARD_PATHNAME: '#/workloads?namespace=default'

  REACT_APP_LOGS_PATHNAME: '/app/discover'
  REACT_APP_TRACE_PATHNAME: '/app/apm/services'
  REACT_APP_METRICS_PATHNAME: '/app/dashboards#/list'

  REACT_APP_IMAGE_URL: 'https://storage.googleapis.com/confixa-files'
  REACT_APP_TRACE_IMG: '/traces.png'
  REACT_APP_LOGS_IMG: '/logs.png'
  REACT_APP_KUBECOST_IMG: '/kubecost.png'
  REACT_APP_METRICS_IMG: '/metrics.png'
  REACT_APP_SYSTEM_HEALTH_IMG: '/system-health.png'
  REACT_APP_ARGOCD_IMG: '/argocd.png'
  REACT_APP_CLUSTER_DASHBOARD_IMG: '/dashboard.png'
  REACT_APP_CONFIGURE_OBSERVABILITY_PDF: '/configure-observability.pdf'
  REACT_APP_CONFIGURE_MONITORING_PDF: '/configure-monitoring.pdf'

  REACT_APP_CRYPTO_KEY: '9JhQB3qbjDwSFYuUGnVLJ5ObQ3xwiWkL'
{{- end }}