{{- if .Values.apiGateway.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.apiGateway.configMapRef }}
data:
  TASK_ID: "c1"
  WORKER_TYPE: "consumer"
  APM_SERVICE_NAME: 'confixa-api'
{{- end }}