{{- if (and (.Values.apiGateway.enable) (.Values.apiGateway.oddSlug.enable)) }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.apiGateway.oddSlug.name }}
spec:
  schedule: "45,15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Values.apiGateway.oddSlug.containerName }}
              image: "{{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag }}"
              command: ["npm", "run", "cron"]
              envFrom:
                - configMapRef:
                    name: {{ .Values.commonConfigMap }}
              env:
                - name: oddSlugCron
                  value: "true"
                - name: REDIS_AUTH_PASS
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.passwordRedisSecretsManagerName }}
                      key: redis-password
                - name: REDIS_HOST
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.passwordSecretsManagerName }}
                      key: redisHost
                - name: RABBITMQ_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.passwordRabbitMQSecretsManagerName }}
                      key: rabbitmq-password
                - name: RABBITMQ_HOST
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.passwordSecretsManagerName }}
                      key: rabbitMQHost
                - name: MONGO_URL
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.passwordSecretsManagerName }}
                      key: mongodbRootHost
                - name: CONFIXA_LLM_KUMA_URL
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.passwordSecretsManagerName }}
                      key: llmKumaHost
              imagePullPolicy: Always
          restartPolicy: OnFailure
{{- end }}
