{{- if (and (.Values.apiGateway.enable) (.Values.apiGateway.argoCdCheckStatus.enable)) }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.apiGateway.argoCdCheckStatus.name }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "30 23 * * *"
  concurrencyPolicy: Forbid  # Prevent overlapping jobs
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 6  # Limit retry attempts
      activeDeadlineSeconds: 300  # 5 minute timeout
      template:
        spec:
          containers:
            - name: {{ .Values.apiGateway.argoCdCheckStatus.containerName }}
              image: "{{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag }}"
              command: ["npm", "run", "cron"]
              envFrom:
                - configMapRef:
                    name: {{ .Values.commonConfigMap }}
              env:
                - name: ARGO_CD_CHECK_STATUS
                  value: "true"
                - name: REDIS_AUTH_PASS
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.passwordRedisSecretsManagerName }}
                      key: redis-password
                - name: REDIS_HOST
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.passwordSecretsManagerName }}
                      key: redisHost
                - name: RABBITMQ_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.passwordRabbitMQSecretsManagerName }}
                      key: rabbitmq-password
                - name: RABBITMQ_HOST
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.passwordSecretsManagerName }}
                      key: rabbitMQHost
                - name: MONGO_URL
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.passwordSecretsManagerName }}
                      key: mongodbRootHost
                - name: CONFIXA_LLM_KUMA_URL
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.passwordSecretsManagerName }}
                      key: llmKumaHost
              imagePullPolicy: Always
              resources:
                requests:
                  memory: {{ .Values.apiGateway.resources.requests.memory }}
                  cpu: {{ .Values.apiGateway.resources.requests.cpu }}
                limits:
                  memory: {{ .Values.apiGateway.resources.limits.memory }}
                  cpu: {{ .Values.apiGateway.resources.limits.cpu }}
          restartPolicy: OnFailure
{{- end }}
