{{- if .Values.apiGateway.enable }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: odd-slug-cron
spec:
  schedule: "45,15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: odd-slug-cron
              image: "{{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag }}"
              command: ["npm", "run", "cron"]
              envFrom:
                - configMapRef:
                    name: {{ .Values.apiGateway.configMapRef }}
                - configMapRef:
                    name: {{ .Values.commonConfigMap }}
              env:
                - name: oddSlugCron
                  value: "true"
                - name: REDIS_AUTH_PASS
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.passwordSecretsManagerName }}
                      key: redisPassword
                - name: ARGOCD_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.passwordSecretsManagerName }}
                      key: argocdPassword
                - name: RABBITMQ_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.passwordSecretsManagerName }}
                      key: rabbitmqPassword
                - name: MONGODB_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.passwordSecretsManagerName }}
                      key: mongodbRootPassword
                - name: MONGODB_USERS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.passwordSecretsManagerName }}
                      key: mongodbUsersPassword
              imagePullPolicy: Always
          restartPolicy: OnFailure
{{- end }}
