## Reference: https://github.com/helm/chart-testing/blob/master/doc/ct_lint-and-install.md
# Don't add the 'debug' attribute, otherwise the workflow won't work anymore
# Only Used for the CT Lint Stage
remote: origin
target-branch: main
chart-dirs:
  - charts
chart-repos:
  bitnami=https://charts.bitnami.com/bitnami,cost-analyzer=https://kubecost.github.io/cost-analyzer,uptime-kuma=https://dirsigler.github.io/uptime-kuma-helm,kubernetes-dashboard=https://kubernetes.github.io/dashboard/
validate-chart-schema: false
validate-maintainers: false
validate-yaml: true
exclude-deprecated: true
excluded-charts: []