repos:
  - repo: local
    hooks:
      - id: helm-docs
        name: Custom Helm Docs
        entry: ./scripts/helm-docs.sh
        language: script

      # - id: helm-lint
      #   name: Custom Lint
      #   entry: ./scripts/lint.sh
      #   language: script
