x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: "$TAG"
  publishedVersionMetadata:
    releaseNote: >-
      Initial release of Confixa platform.
    releaseTypes:
      - Feature
    recommended: false
  images:
    frontend:
      properties:
        frontend.image.repository:
          type: REPO_WITH_REGISTRY
        frontend.image.tag:
          type: TAG
    apiGateway:
      properties:
        apiGateway.image.repository:
          type: REPO_WITH_REGISTRY
        apiGateway.image.tag:
          type: TAG
    argoApi:
      properties:
        argoApi.image.repository:
          type: REPO_WITH_REGISTRY
        argoApi.image.tag:
          type: TAG
    githubActionsApi:
      properties:
        githubActionsApi.image.repository:
          type: REPO_WITH_REGISTRY
        githubActionsApi.image.tag:
          type: TAG
    githubApi:
      properties:
        githubApi.image.repository:
          type: REPO_WITH_REGISTRY
        githubApi.image.tag:
          type: TAG
    licenceApi:
      properties:
        licenceApi.image.repository:
          type: REPO_WITH_REGISTRY
        licenceApi.image.tag:
          type: TAG
    llmBackend:
      properties:
        llmBackend.image.repository:
          type: REPO_WITH_REGISTRY
        llmBackend.image.tag:
          type: TAG
  clusterConstraints:
    resources:
      - replicas: 1
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    istio:
      type: OPTIONAL

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  
  # Redis Configuration
  redis.password:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 16
        base64: true
  
  # MongoDB Configuration
  mongodb.rootPassword:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 16
        base64: true
  mongodb.userPassword:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 16
        base64: true

  # RabbitMQ Configuration
  rabbitmq.password:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 16
        base64: true

  # ArgoCD Configuration
  argocd.adminPassword:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 16
        base64: true

  # Storage Configuration
  persistence.storageClass:
    type: string
    title: StorageClass
    description: StorageClass for persistent volumes
    x-google-marketplace:
      type: STORAGE_CLASS
      storageClass:
        type: SSD

  persistence.size:
    type: string
    title: Storage size for persistent volumes
    default: "20Gi"
    description: Storage size for the application
    pattern: '^[1-9][0-9]*(\.[0-9]+)?[TGM]i?$'

required:
  - name
  - namespace
  - persistence.size
  - redis.password
  - mongodb.rootPassword
  - mongodb.userPassword
  - rabbitmq.password
  - argocd.adminPassword