name: test-confixa
namespace: test-ns
reportingSecret: test-reporting-secret
persistence:
  storageClass: standard
  size: 20Gi
redis:
  password: testredispass
mongodb:
  rootPassword: testmongoroot
  userPassword: testmongouser
rabbitmq:
  password: testrabbitmqpass
argocd:
  adminPassword: testargoadmin

# All the images (marketplace would inject these)
usageReporter:
  image:
    repository: us-docker.pkg.dev/confixa-public/confixa-helm-repo-oci/usagereporter
    tag: 1.2.2
apiGateway:
  image:
    repository: us-docker.pkg.dev/confixa-public/confixa-helm-repo-oci/apigateway
    tag: 1.2.2
frontend:
  image:
    repository: us-docker.pkg.dev/confixa-public/confixa-helm-repo-oci/frontend
    tag: 1.2.2
llmKumaApiGateway:
  image:
    repository: us-docker.pkg.dev/confixa-public/confixa-helm-repo-oci/llmkumaapigateway
    tag: 1.2.2
