{{- if .Values.llmKumaApiGateway.enable }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.llmKumaApiGateway.name }}
  annotations:
    {{- toYaml .Values.llmKumaApiGateway.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.llmKumaApiGateway.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.llmKumaApiGateway.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.llmKumaApiGateway.name }}
    spec:
      containers:
        - name: {{ .Values.llmKumaApiGateway.containerName }}
          image: "{{ .Values.llmKumaApiGateway.image.repository }}:{{ .Values.llmKumaApiGateway.image.tag }}"
          ports:
            - containerPort: {{ .Values.llmKumaApiGateway.ports.containerPort }}
              protocol: {{ .Values.llmKumaApiGateway.ports.protocol }}
          envFrom:
            - configMapRef:
                name: {{ .Values.commonConfigMap }}
{{- end }}