{{- if .Values.llmBackend.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.llmBackend.configMapRef }}
data:
  TASK_ID: "c1"
  WORKER_TYPE: "consumer"
  APM_SERVICE_NAME: "confixa-backend-llm"
{{- end }}