{{- if .Values.supportApi.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.supportApi.name }}
spec:
  selector:
    app: {{ .Values.supportApi.name }}
  ports:
    - protocol: {{ .Values.supportApi.service.protocol }}
      port: {{ .Values.supportApi.service.port }}
      targetPort: {{ .Values.supportApi.service.targetPort }}
  type: {{ .Values.supportApi.service.type }}
{{- end }}