apiVersion: v1
entries:
  Confixa:
  - annotations:
      artifacthub.io/changes: |
        - kind: changed
          description: Bump confixa to 1.0.0
    apiVersion: v2
    appVersion: 1.0.0-rc
    created: "2025-06-26T10:20:54.456785+05:30"
    dependencies:
    - alias: redis
      condition: redis.enable
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 20.2.0
    - alias: rabbitmq
      condition: rabbitmq.enable
      name: rabbitmq
      repository: https://charts.bitnami.com/bitnami
      version: 14.1.4
    description: A Helm chart that deploys confixa-with-microservices-and-dependencies
    digest: add6ca6d21ea572fc453258abe8413858f003816fc0912afd377f80e5bc49995
    home: https://confixa.com
    icon: https://cdn.prod.website-files.com/66aa0bf79ded54ce70cd7daf/66aa27e3568aa2491c2a0c5a_Layer_1.svg
    name: Confixa
    urls:
    - Confixa-1.0.0-rc.tgz
    version: 1.0.0-rc
generated: "2025-06-26T10:20:54.446118+05:30"
