apiVersion: v1
entries:
  Confixa:
  - annotations:
      artifacthub.io/changes: |
        - kind: changed
          description: Bump confixa to 0.0.1
    apiVersion: v2
    appVersion: 0.9.0-rc
    created: "2025-06-24T17:10:05.752532+05:30"
    dependencies:
    - alias: redis
      condition: redis.enable
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 20.2.0
    - alias: rabbitmq
      condition: rabbitmq.enable
      name: rabbitmq
      repository: https://charts.bitnami.com/bitnami
      version: 14.1.4
    description: A Helm chart that deploys confixa-with-microservices-and-dependencies
    digest: 10f8e9a045e534d8bc7d8af0d385fb5337a6b04b501a038227359b423485f995
    home: https://confixa.com
    icon: https://cdn.prod.website-files.com/66aa0bf79ded54ce70cd7daf/66aa27e3568aa2491c2a0c5a_Layer_1.svg
    name: Confixa
    urls:
    - Confixa-0.9.2.tgz
    version: 0.9.2
generated: "2025-06-24T17:10:05.745273+05:30"
