{{- if .Values.oauthApi2.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.oauthApi2.name }}
spec:
  selector:
    app: {{ .Values.oauthApi2.name }}
  ports:
    - protocol: {{ .Values.oauthApi2.service.protocol }}
      port: {{ .Values.oauthApi2.service.port }}
      targetPort: {{ .Values.oauthApi2.service.targetPort }}
  type: {{ .Values.oauthApi2.service.type }}
{{- end }}