{{- if .Values.watcher.enable }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.watcher.name }}
  annotations:
    {{- toYaml .Values.watcher.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.watcher.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.watcher.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.watcher.name }}
    spec:
      serviceAccountName:  {{ .Values.watcher.serviceAccount.serviceAccountRef }}
      containers:
        - name: {{ .Values.watcher.containerName }}
          image: "{{ .Values.watcher.image.repository }}:{{ .Values.watcher.image.tag }}"
          envFrom:
            - secretRef:
                name: {{ .Values.watcher.secret.secretRef.variables }}
          volumeMounts:
            - name: {{ .Values.watcher.serviceAccount.volumeRef }}
              mountPath: {{ .Values.watcher.secret.file.mountPath }}
              readOnly: true
            - name: {{ .Values.watcher.docker.dockerRef }}
              mountPath: {{ .Values.watcher.docker.mountPath }}
      volumes:
        - name: {{ .Values.watcher.serviceAccount.volumeRef }}
          secret:
            secretName: {{ .Values.watcher.secret.secretRef.file }}
        - name: {{ .Values.watcher.docker.dockerRef }}
          hostPath:
            path: {{ .Values.watcher.docker.mountPath }}
            type: {{ .Values.watcher.docker.dockerType }}
      restartPolicy: Always
{{- end }}
