{{- if .Values.watcher.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.watcher.roleBinding.roleBindingRef }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.watcher.role.roleRef }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.watcher.serviceAccount.serviceAccountRef }}
{{- end }}