{{- if .Values.watcher.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.watcher.secret.secretRef.file }}
type: Opaque
data:
  service-account.json: {{ .Values.watcher.secret.file.secretInfo  | b64enc }}
{{- end }}