{{- if .Values.watcher.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.watcher.secret.secretRef.variables }}
type: Opaque
data:
  CONFIGMAP_NAME: {{ .Values.watcher.secret.variables.configMapName | b64enc }}
  DEPLOYMENT_NAME: {{ .Values.watcher.secret.variables.deploymentName | b64enc }}
  CUSTOM_EXEC: {{ .Values.watcher.secret.variables.customExec | b64enc }}
  EXEC_PATH: {{ .Values.watcher.secret.variables.execPath | b64enc }}
  NAMESPACE: {{ .Values.watcher.secret.variables.namespace | b64enc }}
  REPO_URL: {{ .Values.watcher.secret.variables.repoUrl | b64enc }}
  BRANCH: {{ .Values.watcher.secret.variables.branch | b64enc }}
  SERVICE_ACCOUNT_KEY_PATH: {{ .Values.watcher.secret.variables.serviceAccountKeyPath | b64enc }}
  DOCKER_REGION: {{ .Values.watcher.secret.variables.dockerRegion | b64enc }}
  GCR_PROJECT_ID: {{ .Values.watcher.secret.variables.gcrProjectId | b64enc }}
  DOCKER_IMAGE_NAME: {{ .Values.watcher.secret.variables.dockerImageName | b64enc }}
  CONTAINER_NAME: {{ .Values.watcher.secret.variables.containerName | b64enc }}
{{- end }}
