name: DCO Check

on:
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.sh'
      - '**/*.go'
      - '**/*.js'
      - '**/*.ts'

jobs:
  dco:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for DCO sign-off
        uses: idvoretskyi/dcochecker@v1

